### ISSUE TITLE
ModuleNotFoundError: No module named 'lib2to3.fixes'

### ISSUE THREAD

**Issue by hoiyada** [wsder31/mechanical_scraper#1]
코드로 가져와서 하니 동작하는데 ,exe 파일은 해당 에러 발생하네요
<img width="497" alt="화면 캡처 2023-09-15 084401" src="https://github.com/wsder31/mechanical_scraper/assets/17831023/be06a560-4a90-4d37-93a4-46ee5ca4d782">

**Comment by wsder31** [comment]
I'm sorry for the late answer. You can run it properly via v3.2 now. Thank you.
